apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name  }}
  labels:
    run: {{ .Values.name }}
spec:
  containers:
  - image: {{ .Values.image }}:{{ .Values.tag }}
    name: {{ .Values.name }}
    ports:
    - containerPort: {{ .Values.port }}
